import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import Editor from '@/views/Editor.vue'

/**
 * Characterization tests for the Editor view.
 *
 * The Editor deep-copies initialForm into a reactive form, coerces null
 * title/description to '' (#134 — NcTextField crashes on null), and derives
 * permission/page computeds. It fires presence heartbeats on an interval, so
 * fake timers keep the interval deterministic.
 */

const fullPerms = {
	editQuestions: true,
	editSettings: true,
	viewResponses: true,
	canShare: true,
}

const baseForm = () => ({
	title: 'My form',
	description: 'Desc',
	questions: [],
	pages: [],
	settings: {},
	permissions: {},
	branding: {},
})

const mountEditor = (overrides = {}) => {
	const props = {
		fileId: 123,
		initialForm: overrides.initialForm ?? baseForm(),
		role: overrides.role ?? 'owner',
		permissions: overrides.permissions ?? fullPerms,
	}
	return mount(Editor, { props })
}

describe('views/Editor', () => {
	beforeEach(() => {
		vi.useFakeTimers()
	})
	afterEach(() => {
		vi.runOnlyPendingTimers()
		vi.useRealTimers()
	})

	it('mounts and renders the title field', () => {
		const wrapper = mountEditor()
		expect(wrapper.find('[data-stub="NcTextField"]').exists()).toBe(true)
	})

	it('coerces a null title to empty string (#134)', () => {
		const form = baseForm()
		form.title = null
		const wrapper = mountEditor({ initialForm: form })
		expect(wrapper.vm.form.title).toBe('')
	})

	it('coerces an undefined title to empty string (#134)', () => {
		const form = baseForm()
		delete form.title
		const wrapper = mountEditor({ initialForm: form })
		expect(wrapper.vm.form.title).toBe('')
	})

	it('coerces a null description to empty string (#134)', () => {
		const form = baseForm()
		form.description = null
		const wrapper = mountEditor({ initialForm: form })
		expect(wrapper.vm.form.description).toBe('')
	})

	it('preserves a real title', () => {
		const wrapper = mountEditor()
		expect(wrapper.vm.form.title).toBe('My form')
	})

	it('deep-copies initialForm — mutations do not leak back to the prop', () => {
		const form = baseForm()
		const wrapper = mountEditor({ initialForm: form })
		wrapper.vm.form.title = 'changed'
		expect(form.title).toBe('My form')
	})

	it('hasPages is false with no pages, true once a page exists', async () => {
		const wrapper = mountEditor()
		expect(wrapper.vm.hasPages).toBe(false)
		wrapper.vm.form.pages = [{ id: 'p1', title: '', questions: [] }]
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.hasPages).toBe(true)
	})

	it('togglePages enables pages, moving existing question ids onto page 1', async () => {
		const form = baseForm()
		form.questions = [{ id: 'q1', type: 'text' }, { id: 'q2', type: 'text' }]
		const wrapper = mountEditor({ initialForm: form })
		wrapper.vm.togglePages()
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.hasPages).toBe(true)
		expect(wrapper.vm.form.pages[0].questions).toEqual(['q1', 'q2'])
	})

	it('togglePages again disables pages', async () => {
		const wrapper = mountEditor()
		wrapper.vm.togglePages()
		wrapper.vm.togglePages()
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.hasPages).toBe(false)
	})

	it('addQuestion appends a text question', async () => {
		const wrapper = mountEditor()
		wrapper.vm.addQuestion()
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.questions.length).toBe(1)
		expect(wrapper.vm.form.questions[0].type).toBe('text')
	})

	it('addSection appends a section item', async () => {
		const wrapper = mountEditor()
		wrapper.vm.addSection()
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.questions.at(-1).type).toBe('section')
	})

	it('addDescriptor appends a descriptor item', async () => {
		const wrapper = mountEditor()
		wrapper.vm.addDescriptor()
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.questions.at(-1).type).toBe('descriptor')
	})

	it('visibleFormQuestions hides auto-generated questions', () => {
		const form = baseForm()
		form.questions = [
			{ id: 'q1', type: 'text' },
			{ id: 'q2', type: 'email', autoGenerated: true },
		]
		const wrapper = mountEditor({ initialForm: form })
		expect(wrapper.vm.visibleFormQuestions.map(q => q.id)).toEqual(['q1'])
	})

	it('getQuestionIndex finds by id and returns -1 when missing', () => {
		const form = baseForm()
		form.questions = [{ id: 'q1', type: 'text' }]
		const wrapper = mountEditor({ initialForm: form })
		expect(wrapper.vm.getQuestionIndex('q1')).toBe(0)
		expect(wrapper.vm.getQuestionIndex('nope')).toBe(-1)
	})

	it('deleteQuestion removes by index', async () => {
		const form = baseForm()
		form.questions = [{ id: 'q1', type: 'text' }, { id: 'q2', type: 'text' }]
		const wrapper = mountEditor({ initialForm: form })
		wrapper.vm.deleteQuestion(0)
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.questions.map(q => q.id)).toEqual(['q2'])
	})

	it('duplicateQuestion inserts a copy with a fresh id after the original', async () => {
		const form = baseForm()
		form.questions = [{ id: 'q1', type: 'text', question: 'Hi' }]
		const wrapper = mountEditor({ initialForm: form })
		wrapper.vm.duplicateQuestion(0)
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.questions.length).toBe(2)
		expect(wrapper.vm.form.questions[1].question).toBe('Hi')
		expect(wrapper.vm.form.questions[1].id).not.toBe('q1')
	})

	it('publicPreviewUrl is null without a public token', () => {
		const wrapper = mountEditor()
		expect(wrapper.vm.publicPreviewUrl).toBe(null)
	})

	it('publicPreviewUrl builds a link when a public token exists', async () => {
		const form = baseForm()
		form.settings = { public_token: 'tok123' }
		const wrapper = mountEditor({ initialForm: form })
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.publicPreviewUrl).toBe('/apps/formvox/public/123/tok123')
	})

	it('canEdit reflects editQuestions permission', () => {
		const wrapper = mountEditor({ permissions: { ...fullPerms, editQuestions: false } })
		expect(wrapper.vm.canEdit).toBe(false)
	})

	it('canViewResponses reflects the viewResponses permission', () => {
		const wrapper = mountEditor({ permissions: { ...fullPerms, viewResponses: false } })
		expect(wrapper.vm.canViewResponses).toBe(false)
	})

	it('canShare reflects the canShare permission', () => {
		const wrapper = mountEditor({ permissions: { ...fullPerms, canShare: false } })
		expect(wrapper.vm.canShare).toBe(false)
	})

	it('lockedByOther is false with no active editors', () => {
		const wrapper = mountEditor()
		expect(wrapper.vm.lockedByOther).toBe(false)
	})

	it('lockedByOther becomes true when another editor arrived first', async () => {
		const wrapper = mountEditor()
		// Let the on-mount presence fetch settle first, else it overwrites us.
		await flushPromises()
		wrapper.vm.activeEditors = [{ userId: 'bob', firstSeen: 100 }]
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.lockedByOther).toBe(true)
		// and lockingEditor is that earliest editor
		expect(wrapper.vm.lockingEditor.userId).toBe('bob')
	})

	it('canEdit is false while locked by another editor even with permission', async () => {
		const wrapper = mountEditor()
		await flushPromises()
		wrapper.vm.activeEditors = [{ userId: 'bob', firstSeen: 100 }]
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.canEdit).toBe(false)
	})

	it('addPage adds a page only when pages are enabled', async () => {
		const wrapper = mountEditor()
		wrapper.vm.addPage() // no-op, pages disabled
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.hasPages).toBe(false)
		wrapper.vm.togglePages()
		wrapper.vm.addPage()
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.pages.length).toBe(2)
	})

	it('deletePage relocates its questions onto a neighbour page', async () => {
		const form = baseForm()
		form.pages = [
			{ id: 'p1', title: 'A', questions: ['q1'] },
			{ id: 'p2', title: 'B', questions: ['q2'] },
		]
		form.questions = [{ id: 'q1', type: 'text' }, { id: 'q2', type: 'text' }]
		const wrapper = mountEditor({ initialForm: form })
		wrapper.vm.deletePage(1)
		await wrapper.vm.$nextTick()
		expect(wrapper.vm.form.pages.length).toBe(1)
		// q2 moved onto the surviving previous page
		expect(wrapper.vm.form.pages[0].questions).toContain('q2')
	})

	it('currentPageQuestions returns the resolved question objects for the active page', async () => {
		const form = baseForm()
		form.pages = [{ id: 'p1', title: '', questions: ['q1', 'q2'] }]
		form.questions = [
			{ id: 'q1', type: 'text' },
			{ id: 'q2', type: 'email', autoGenerated: true },
		]
		const wrapper = mountEditor({ initialForm: form })
		await wrapper.vm.$nextTick()
		// auto-generated q2 is hidden from the editor list (#103)
		expect(wrapper.vm.currentPageQuestions.map(q => q.id)).toEqual(['q1'])
	})
})
